### ISSUE TITLE
jalanin project gimana?

### ISSUE THREAD

**Issue by Muhammad-Yuda-Yudistira** [iqballa24/Noto-app#3]
mas ini jalanin projectnya bukan npm start ya? kenapa npm star? tapi saya ga bisa jalanin juga, ntah error dari cli sayanya

**Comment by iqballa24** [comment]
iya bukan npm start mas,  klo mau ngerun bisa dgn command "npm run dev". Bisa diliat detailnya dan juga diubah di file package.json bagian scripts
