### ISSUE TITLE
tidak dapat menjalankan server. npm start

### ISSUE THREAD

**Issue by Muhammad-Yuda-Yudistira** [iqballa24/Noto-app#4]
mas saya beberapa hari lalu bertanya tentang project mas ini. saya tidak dapat menjalankan servernya, silahkan lihat screenshootnya di url berikut mas: https://ibb.co/gW4DP9g 

mohon bantuannya mas, terima kasih

**Comment by iqballa24** [comment]
jalanin projectnya dengan command "npm run dev" mas, bukan npm start
